In [15]:
import pandas as pd

df = pd.read_csv('Police_Department_Incident_Reports__2018_to_Present_20240406.csv')
df

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/13 11:41:00 PM,2023/03/13,23:41,2023,Monday,2023/03/13 11:41:00 PM,125373607041,1253736,230167874,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/13 01:16:00 PM,2023/03/13,13:16,2023,Monday,2023/03/13 01:17:00 PM,125357107041,1253571,220343896,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839464,2023/03/22 01:30:00 PM,2023/03/22,13:30,2023,Wednesday,2023/03/22 01:35:00 PM,125685303401,1256853,230201949,230811847.0,...,-122.406336,POINT (-122.40633623830558 37.75300402962228),54.0,NaN,NaN,NaN,3.0,NaN,2.0,3.0
839465,2023/03/22 12:13:00 AM,2023/03/22,00:13,2023,Wednesday,2023/03/22 12:13:00 AM,125665206371,1256652,230200838,230810020.0,...,-122.440624,POINT (-122.44062361999508 37.78899525864335),102.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0
839466,2023/03/21 09:19:00 PM,2023/03/21,21:19,2023,Tuesday,2023/03/21 10:16:00 PM,125664272000,1256642,230200800,230803734.0,...,-122.452665,POINT (-122.45266472219633 37.70880633652071),66.0,NaN,NaN,NaN,NaN,NaN,1.0,9.0
839467,2023/03/22 03:28:00 PM,2023/03/22,15:28,2023,Wednesday,2023/03/22 05:51:00 PM,125687306303,1256873,230202486,230812680.0,...,-122.405574,POINT (-122.40557374633903 37.790565236529574),19.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0
839468,2023/03/21 05:42:00 PM,2023/03/21,17:42,2023,Tuesday,2023/03/22 09:40:00 AM,125676707021,1256767,230201450,230811015.0,...,-122.402056,POINT (-122.40205647302719 37.72127745117722),91.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 839469 entries, 0 to 839468
Data columns (total 35 columns):
 #   Column                                                Non-Null Count   Dtype
---  ------                                                --------------   -----
 0   Incident Datetime                                     839469 non-null  object
 1   Incident Date                                         839469 non-null  object
 2   Incident Time                                         839469 non-null  object
 3   Incident Year                                         839469 non-null  int64
 4   Incident Day of Week                                  839469 non-null  object
 5   Report Datetime                                       839469 non-null  object
 6   Row ID                                                839469 non-null  int64
 7   Incident ID                                           839469 non-null  int64
 8   Incident Number                                       839469 non-null  int64
 9   CAD Number                                            649858 non-null  float64
 10  Report Type Code                                      839469 non-null  object
 11  Report Type Description                               839469 non-null  object
 12  Filed Online                                          168922 non-null  object
 13  Incident Code                                         839469 non-null  int64
 14  Incident Category                                     838695 non-null  object
 15  Incident Subcategory                                  838695 non-null  object
 16  Incident Description                                  839469 non-null  object
 17  Resolution                                            839469 non-null  object
 18  Intersection                                          793140 non-null  object
 19  CNN                                                   793140 non-null  float64
 20  Police District                                       839469 non-null  object
 21  Analysis Neighborhood                                 792983 non-null  object
 22  Supervisor District                                   792700 non-null  float64
 23  Supervisor District 2012                              793000 non-null  float64
 24  Latitude                                              793140 non-null  float64
 25  Longitude                                             793140 non-null  float64
 26  Point                                                 793140 non-null  object
 27  Neighborhoods                                         776762 non-null  float64
 28  ESNCAG - Boundary File                                8859 non-null    float64
 29  Central Market/Tenderloin Boundary Polygon - Updated  109210 non-null  float64
 30  Civic Center Harm Reduction Project Boundary          107913 non-null  float64
 31  HSOC Zones as of 2018-06-05                           174379 non-null  float64
 32  Invest In Neighborhoods (IIN) Areas                   0 non-null       float64
 33  Current Supervisor Districts                          793000 non-null  float64
 34  Current Police Districts                              792261 non-null  float64
dtypes: float64(14), int64(5), object(16)
memory usage: 224.2+ MB

In [20]:
df['Incident Category'].value_counts()

Incident Category
Larceny Theft                                   253665
Other Miscellaneous                              56901
Malicious Mischief                               56847
Assault                                          51293
Non-Criminal                                     49130
Burglary                                         46618
Motor Vehicle Theft                              45432
Recovered Vehicle                                33917
Fraud                                            27342
Lost Property                                    24535
Warrant                                          24077
Drug Offense                                     21010
Robbery                                          18868
Missing Person                                   18064
Suspicious Occ                                   17216
Disorderly Conduct                               14347
Offences Against The Family And Children         11048
Miscellaneous Investigation                       9358
Traffic Violation Arrest                          7805
Other Offenses                                    7205
Other                                             7041
Weapons Offense                                   5825
Weapons Carrying Etc                              4663
Stolen Property                                   4066
Case Closure                                      3252
Forgery And Counterfeiting                        2904
Courtesy Report                                   2532
Arson                                             2421
Traffic Collision                                 2007
Vandalism                                         1913
Fire Report                                       1246
Embezzlement                                      1048
Civil Sidewalks                                    889
Sex Offense                                        860
Prostitution                                       854
Vehicle Impounded                                  615
Suicide                                            372
Vehicle Misplaced                                  359
Drug Violation                                     280
Rape                                               205
Homicide                                           152
Liquor Laws                                        115
Suspicious                                         114
Human Trafficking (A), Commercial Sex Acts         113
Motor Vehicle Theft?                                86
Gambling                                            38
Human Trafficking, Commercial Sex Acts              23
Weapons Offence                                     23
Human Trafficking (B), Involuntary Servitude         1
Name: count, dtype: int64

In [25]:
df.dropna(subset=['Latitude', 'Longitude'], inplace=True)

In [30]:
# Assualt, Robbery, Vandalism, Motor Vehicle theft, 
subset_df = df[(df['Incident Category'] == 'Assualt') | (df['Incident Category'] == 'Robbery') | (df['Incident Category'] == 'Vandalism') | (df['Incident Category'] == 'Motor Vehicle theft') | (df['Incident Description'] == 'GRAND THEFT FROM LOCKED AUTO')][['Incident Datetime','Incident Category','Incident Description','Latitude', 'Longitude']]

In [31]:
subset_df

,Incident Datetime,Incident Category,Incident Description,Latitude,Longitude
677,2021/07/18 08:30:00 AM,Robbery,"Robbery, W/ Gun",37.787087,-122.421560
723,2021/11/17 06:51:00 PM,Robbery,"Robbery, W/ Force",37.722240,-122.443793
872,2022/04/01 01:50:00 AM,Robbery,"Robbery, W/ Force",37.736061,-122.424466
931,2022/11/12 10:00:00 PM,Vandalism,"Vehicle, Tampering",37.738473,-122.494721
934,2022/02/03 02:09:00 AM,Vandalism,"Vehicle, Tampering",37.771571,-122.442188
...,...,...,...,...,...
839342,2023/03/21 12:30:00 PM,Robbery,"Robbery, W/ Force",37.726588,-122.433357
839385,2023/03/22 06:41:00 PM,Robbery,"Robbery, Street or Public Place, W/ Gun",37.725304,-122.378951
839446,2023/03/17 08:30:00 PM,Robbery,"Robbery, W/ Gun",37.763656,-122.474985
839454,2023/03/16 09:00:00 PM,Robbery,"Robbery, W/ Gun",37.752739,-122.410066
839464,2023/03/22 01:30:00 PM,Robbery,"Shoplifting, Force against Agent",37.753004,-122.406336

In [80]:
subset_df.drop(['Distance', 'Distance2'], inplace=True, axis=1)

In [83]:
subset_df['Incident Datetime'] = pd.to_datetime(subset_df['Incident Datetime'], format='%Y/%m/%d %I:%M:%S %p')

In [87]:
subset_df.iloc[0]['Incident Datetime']

7

In [88]:
subset_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20636 entries, 677 to 839464
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Incident Datetime     20636 non-null  datetime64[ns]
 1   Incident Category     20636 non-null  object
 2   Incident Description  20636 non-null  object
 3   Latitude              20636 non-null  float64
 4   Longitude             20636 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 1.4+ MB

In [89]:
subset_df.to_csv('crime_df.csv',index=False)

In [90]:
from geopy.distance import geodesic
target_lat = 37.787087
target_lon = -122.421560

# Define the search radius (in kilometers)
search_radius = 5  # You can adjust this value as per your requirement

# Create a function to calculate the distance between two coordinates
def get_distance(lat1, lon1, lat2, lon2):
    return geodesic((lat1, lon1), (lat2, lon2)).km

In [93]:
subset_df['Distance'] = subset_df.apply(lambda row: get_distance(row['Latitude'], row['Longitude'], target_lat, target_lon), axis=1)

In [94]:
subset_df

,Incident Datetime,Incident Category,Incident Description,Latitude,Longitude,Distance2,Distance
677,2021-07-18 08:30:00,Robbery,"Robbery, W/ Gun",37.787087,-122.421560,0.000037,0.000037
723,2021-11-17 18:51:00,Robbery,"Robbery, W/ Force",37.722240,-122.443793,7.459357,7.459357
872,2022-04-01 01:50:00,Robbery,"Robbery, W/ Force",37.736061,-122.424466,5.669244,5.669244
931,2022-11-12 22:00:00,Vandalism,"Vehicle, Tampering",37.738473,-122.494721,8.406663,8.406663
934,2022-02-03 02:09:00,Vandalism,"Vehicle, Tampering",37.771571,-122.442188,2.503612,2.503612
...,...,...,...,...,...,...,...
839342,2023-03-21 12:30:00,Robbery,"Robbery, W/ Force",37.726588,-122.433357,6.794876,6.794876
839385,2023-03-22 18:41:00,Robbery,"Robbery, Street or Public Place, W/ Gun",37.725304,-122.378951,7.818045,7.818045
839446,2023-03-17 20:30:00,Robbery,"Robbery, W/ Gun",37.763656,-122.474985,5.377451,5.377451
839454,2023-03-16 21:00:00,Robbery,"Robbery, W/ Gun",37.752739,-122.410066,3.944556,3.944556
839464,2023-03-22 13:30:00,Robbery,"Shoplifting, Force against Agent",37.753004,-122.406336,4.013695,4.013695

In [102]:
subset_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20636 entries, 677 to 839464
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Incident Datetime     20636 non-null  datetime64[ns]
 1   Incident Category     20636 non-null  object
 2   Incident Description  20636 non-null  object
 3   Latitude              20636 non-null  float64
 4   Longitude             20636 non-null  float64
 5   Distance2             20636 non-null  float64
 6   Distance              20636 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(2)
memory usage: 1.8+ MB

In [103]:
df = pd.read_csv('crime_df.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20636 entries, 0 to 20635
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Incident Datetime     20636 non-null  object
 1   Incident Category     20636 non-null  object
 2   Incident Description  20636 non-null  object
 3   Latitude              20636 non-null  float64
 4   Longitude             20636 non-null  float64
dtypes: float64(2), object(3)
memory usage: 806.2+ KB

In [104]:
df['Incident Datetime'] = pd.to_datetime(df['Incident Datetime'], format='%Y/%m/%d %I:%M:%S %p')

ValueError: time data "2021-07-18 08:30:00" doesn't match format "%Y/%m/%d %I:%M:%S %p", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [96]:
from datetime import datetime, timedelta
threshold = 1

last_month_start = datetime.now().replace(day=1) - timedelta(days=1)
last_month_start = last_month_start.replace(day=1)
last_month_end = datetime.now().replace(day=1) - timedelta(days=1)

last_month_start = pd.Timestamp(last_month_start)
last_month_end = pd.Timestamp(last_month_end)

last_month_start

datetime.datetime(2024, 3, 1, 21, 15, 19, 781150)

In [97]:
subset_df.iloc[0]['Incident Datetime']

Timestamp('2021-07-18 08:30:00')

In [101]:
filtered_df = subset_df[(subset_df['Distance'] < threshold) & (subset_df['Incident Datetime'] >= last_month_start) & (subset_df['Incident Datetime'] <= last_month_end)]

# Print the filtered DataFrame
filtered_df

,Incident Datetime,Incident Category,Incident Description,Latitude,Longitude,Distance2,Distance
122002,2024-03-23 16:05:00,Robbery,"Robbery, Att., W/ Force",37.784451,-122.416069,0.565316,0.565316
130273,2024-03-09 11:30:00,Robbery,"Robbery, Chain Store, W/ Knife",37.790577,-122.420685,0.394953,0.394953
130547,2024-03-11 04:35:00,Robbery,"Robbery, W/ Force",37.783722,-122.414238,0.745319,0.745319
131044,2024-03-24 02:41:00,Robbery,"Robbery, Street or Public Place, W/ Gun",37.786312,-122.416451,0.458221,0.458221
131427,2024-03-14 11:43:00,Robbery,"Robbery, Street or Public Place, W/ Force",37.781864,-122.413864,0.891976,0.891976
131433,2024-03-14 17:30:00,Robbery,"Robbery, Street or Public Place, W/ Force",37.781864,-122.413864,0.891976,0.891976
131546,2024-03-14 17:15:00,Robbery,"Robbery, W/ Force",37.785789,-122.412971,0.770117,0.770117
131565,2024-03-11 04:35:00,Robbery,"Robbery, W/ Force",37.783722,-122.414238,0.745319,0.745319
132459,2024-03-24 12:45:00,Robbery,"Shoplifting, Force against Agent",37.789619,-122.420494,0.296349,0.296349
132498,2024-03-16 18:48:00,Robbery,"Shoplifting, Force against Agent",37.787548,-122.421761,0.054138,0.054138
132975,2024-03-18 15:31:00,Robbery,"Robbery, Att., W/ Force",37.784866,-122.412781,0.811666,0.811666
133230,2024-03-19 07:55:00,Robbery,"Robbery, W/ Force",37.783722,-122.414238,0.745319,0.745319
133338,2024-03-19 12:55:00,Robbery,"Robbery, W/ Force",37.785789,-122.412971,0.770117,0.770117
134056,2024-03-20 23:38:00,Robbery,"Robbery, W/ Knife",37.785374,-122.431366,0.884461,0.884461
134196,2024-03-14 09:30:00,Robbery,"Robbery, Street or Public Place, W/ Knife",37.790787,-122.419037,0.466928,0.466928
134342,2024-03-22 08:10:00,Robbery,"Robbery, W/ Force",37.785725,-122.416328,0.485006,0.485006
134356,2024-03-21 19:15:00,Robbery,"Robbery, W/ Force",37.786617,-122.421570,0.052143,0.052143
134835,2024-03-24 17:30:00,Robbery,"Robbery, W/ Force",37.783924,-122.427780,0.650735,0.650735
135019,2024-03-25 13:41:00,Robbery,"Robbery, Street or Public Place, W/ Other Weapon",37.780617,-122.416138,0.862487,0.862487
135428,2024-03-27 00:15:00,Robbery,"Robbery, Street or Public Place, W/ Force",37.787247,-122.416641,0.433635,0.433635
136117,2024-03-31 04:15:00,Robbery,"Robbery, Street or Public Place, W/ Force",37.786102,-122.418091,0.324544,0.324544